<?php

namespace Database\Seeders;

use App\Models\ProductCategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;


class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // \App\Models\Product::factory(1000)->create();

        $items = [
            'Sapu Lidi',
            'Penggaris',
            'Kunci Pas 12',
            'Baju Tidur Anak',
            'Sikat Gigi Elektrik',
            'Kaos Kaki Polos',
            'Tas Laptop',
            'Topi Baseball',
            'Pisau Dapur',
            'Bantal Sofa',
            'Earphone',
            'Buku Cerita Anak',
            'Mouse Wireless',
            'Sarung Tangan Kulit',
            'Flashdisk 32GB',
            'Lampu Belajar',
            'Sandal Jepit',
            'Tas Selempang',
            'Sepatu Sneakers',
            'Cangkir Keramik',
            'Keyboard Gaming',
            'Gunting Kuku',
            'Kacamata Renang',
            'Pensil Warna',
            'Speaker Bluetooth',
            'Jam Dinding',
            'Botol Minum Stainless',
            'Cincin Perak',
            'Tas Ransel Sekolah',
            'Piring Melamin',
            'Gelang Fashion',
            'Alat Cukur Elektrik',
            'Sepatu Boots',
            'Boneka Beruang',
            'Baju Olahraga',
            'Papan Tulis Whiteboard',
            'Pisau Lipat',
            'Kaos Kaki Anak',
            'Laptop Stand',
            'Kipas Angin Meja',
            'Gantungan Kunci',
            'Kemeja Pria',
            'Celana Jeans Wanita',
            'Celemek Dapur',
            'Masker Wajah',
            'Tali Jemuran',
            'Kemeja Wanita',
            'Pulpen Gel',
            'Sikat Cuci Piring',
            'Kursi Lipat',
            'Tas Tidur Camping',
            'Penghapus Karet',
            'Kamera Action',
            'Buku Agenda',
            'Kotak P3K',
            'Gembok Koper',
            'Topi Fedora',
            'Tas Serut',
            'Gelas Minum',
            'Tas Pinggang',
            'Kalkulator',
            'Kertas Origami',
            'Pisau Daging',
            'Sepatu Formal',
            'Bantal Guling',
            'Keranjang Belanja',
            'Tas Travelling',
            'Tempat Pensil',
            'Payung Lipat',
            'Kunci Inggris',
            'Penghapus Whiteboard',
            'Sarung Bantal Sofa',
            'Baju Renang Anak',
            'Tas Sepeda',
            'Speaker Mini',
            'Buku Catatan',
            'Kotak Perhiasan',
            'Celana Jogger',
            'Sapu Seret',
            'Tas Kamera',
            'Kabel Data',
            'Pelindung Lutut',
            'Kursi Plastik',
            'Pensil Mekanik',
            'Gunting Kertas',
            'Baju Koko',
            'Kipas Angin Gantung',
            'Tas Serbaguna',
            'Botol Parfum',
            'Buku Masak',
            'Sepatu Sandal Wanita',
            'Pisau Serbaguna',
            'Topi Trucker',
            'Gantungan Handuk',
            'Sepatu Futsal',
            'Sajadah',
            'Tas Makeup',
            'Tas Sekolah Anak',
            'Tas Pingpong',
            'Boneka Barbie',
            'Tas Selempang Wanita',
            'Buku Pelajaran',
            'Kunci L',
            'Celana Pendek Pria',
            'Kacamata Hitam',
            'Gunting Rambut',
            'Baju Anak Perempuan',
            'Tas Bahu',
            'Lemari Pakaian',
            'Buku Tafsir',
            'Tas Pantai',
            'Kotak Tisu',
            'Sandal Gunung',
            'Sarung Bantal Kursi',
            'Tempat Tidur Lipat',
            'Alat Cukur Kumis',
            'Gembok Motor',
            'Topi Pria',
            'Buku Fiksi',
            'Baju Muslimah',
            'Kemeja Formal',
            'Laptop Sleeve',
            'Bantal Leher',
            'Kotak Pensil',
            'Kipas Angin Mini',
            'Pensil Teknik',
            'Sarung Tangan Motor',
            'Sepatu Pantofel',
            'Buku Komik',
            'Tas Kulit',
            'Payung Golf',
            'Kotak Pakaian',
            'Tas Sport',
            'Pisau Set',
            'Topi Wanita',
            'Kaos Oblong',
            'Tas Selempang Pria',
            'Tas Kamera DSLR',
            'Piring Makan',
            'Sandal Jepit Wanita',
            'Gunting Kain',
            'Baju Tidur Wanita',
            'Tas Selempang Kulit',
            'Senter LED',
            'Pensil Warna Set',
            'Alat Cuci Mobil',
            'Kursi Roda',
            'Sepatu Gunung',
            'Baju Kerja Wanita',
            'Celana Legging',
            'Kotak Sepatu',
            'Buku Pendidikan',
            'Tas Ransel Laptop',
            'Kotak P3K Mobil',
            'Gembok Sepeda',
            'Topi Snapback',
            'Tas Pinggang Kulit',
            'Keranjang Buah',
            'Baju Muslim Pria',
            'Tas Makeup Travel',
            'Tas Selempang Canvas',
            'Payung Lipat Mini',
            'Gunting Kuku Anak',
            'Kotak Kado',
            'Kabel Charger',
            'Pensil Hb',
            'Sikat Cuci Botol',
            'Kursi Makan Anak',
            'Tas Gendong Bayi',
            'Sepatu Sandal Pria',
            'Buku Agama',
            'Kain Lap',
            'Baju Batik Wanita',
            'Kemeja Batik Pria',
            'Sandal Gunung Wanita',
            'Buku Anak',
            'Tas Selempang Kanvas',
            'Pisau Lipat Multifungsi',
            'Topi Baseball Wanita',
            'Tas Punggung',
            'Gunting Kertas Anak',
            'Pensil Warna Polycolor',
            'Alat Sulap',
            'Kotak Makan',
            'Tas Travelling Wanita',
            'Keranjang Mainan Anak',
            'Sikat Toilet',
            'Tas Punggung Anak',
            'Gunting Kuku Besar',
            'Baju Kebaya',
            'Tas Serut Canvas',
            'Pisau Dapur Set',
            'Gelang Kayu',
            'Kotak Perhiasan Kayu',
            'Topi Fedora Pria',
            'Tas Selempang Pria Kulit',
            'Baju Renang Muslimah',
            'Kursi Roda Lipat',
            'Sandal Gunung Pria',
            'Tas Ransel Laptop Wanita',
            'Tas Makeup Organizer',
            'Buku Cerita Bergambar',
            'Sajadah Lipat',
            'Tas Pinggang Kulit Pria',
            'Kotak Pensil Kayu',
            'Pensil Warna Prismacolor',
            'Sapu Seret Aluminium',
            'Kain Kasa',
            'Baju Batik Pria',
            'Tas Selempang Kulit Wanita',
            'Topi Fedora Wanita',
            'Tas Pinggang Kulit Wanita',
            'Kursi Makan Bayi',
            'Kemeja Flanel Pria',
            'Sandal Pantai',
            'Tas Ransel Sekolah Anak',
            'Pisau Dapur Stainless',
            'Gelang Manik',
            'Topi Snapback Pria',
            'Tas Serut Kulit',
            'Baju Renang Muslim',
            'Kursi Lipat Aluminium',
            'Sandal Pantai Wanita',
            'Tas Ransel Laptop Pria',
            'Gembok Koper TSA',
            'Topi Fedora Kulit',
            'Tas Serut Canvas Wanita',
            'Sarung Bantal Sofa Motif',
            'Gunting Kertas Kecil',
            'Pensil Warna Faber Castell',
            'Sapu Seret Kayu',
            'Tas Selempang Pria Kulit Asli',
            'Buku Cerita Islami',
            'Tas Pinggang Kulit Asli',
            'Kotak P3K Mobil Terlengkap',
            'Pisau Dapur Keramik',
            'Gelang Karet',
            'Topi Fedora Pria Kulit',
            'Tas Pinggang Kulit Asli Wanita',
            'Sandal Gunung Pria Kulit',
            'Tas Selempang Pria Kulit Sapi',
            'Baju Renang Muslimah Murah',
            'Kursi Roda Lipat Ringan',
            'Sandal Gunung Wanita Kulit',
            'Tas Ransel Laptop Wanita Murah',
            'Tas Makeup Organizer Lipat',
            'Buku Cerita Bergambar Anak',
            'Sajadah Lipat Murah',
            'Tas Pinggang Kulit Asli Pria',
            'Kotak Pensil Kayu Minimalis',
            'Pensil Warna Prismacolor Asli',
            'Sapu Seret Aluminium Anti Lengket',
            'Kain Kasa Murah',
            'Baju Batik Pria Modern',
            'Tas Selempang Kulit Wanita Asli',
            'Topi Fedora Wanita Asli',
            'Tas Pinggang Kulit Asli Wanita Murah',
            'Kursi Makan Bayi Terbaru',
            'Kemeja Flanel Pria Murah',
            'Sandal Pantai Murah',
            'Tas Ransel Sekolah Anak Terbaik',
            'Pisau Dapur Stainless Berkualitas',
            'Gelang Manik Cantik',
            'Topi Snapback Pria Keren',
            'Tas Serut Kulit Asli',
            'Baju Renang Muslim Elegan',
            'Kursi Lipat Aluminium Anti Lengket',
            'Sandal Pantai Wanita Cantik',
            'Tas Ransel Laptop Pria Terbaru',
            'Gembok Koper TSA Anti Lengket',
            'Topi Fedora Kulit Asli',
            'Tas Serut Canvas Wanita Asli',
            'Sarung Bantal Sofa Motif Lucu',
            'Gunting Kertas Kecil Tahan Lama',
            'Pensil Warna Faber Castell Asli'
        ];

        $product_category = ProductCategory::inRandomOrder()->first();

        foreach ($items as $item) {
            \App\Models\Product::create([
                'name' => $item,
                'description' => $item . ". " . fake()->text(rand(100, 150)),
                'image' => fake()->imageUrl(640, 640),
                'price' => fake()->numberBetween(1000, 100000),
                'slug' => Str::slug($item),
                'product_category_id' => $product_category->id,
                'weight' => fake()->numberBetween(100, 1000),
            ]);
        }
    }
}
